name=TinyBeacon
ver
ion=1.0.0
author=TinyBeacon
maintainer=TinyBeacon
sentence=A library for dynamic BLE-based provisioning of WiFi and custom fields on ESP32.
paragraph=Pairs with a provisioner app and backend to retrieve custom branding and dynamic fields dynamically, provisioning ESP32 over BLE.
category=Communication
url=https://github.com/kennycoder/tiny-beacon
architectures=esp32
includes=TinyBeacon.h
